### ISSUE TITLE
Incompatibility with MATLAB R2014b

### ISSUE THREAD

**Issue by lm808** [zprime/matlabfrag#11]
Dear zprime,

MATLAB R2014b has a new figure/graphics system, which has caused incompatibilities with matlabfrag.
Just wondering whether you would be releasing an update soon?

The two issues I have encountered so far:
1) No '$' added to tick-marks when using log scale. i.e. when tick-marks are in the form of "10^{2}", no "$" will be automatically added any more.
2) Legend does not get formatted any more, due to the fact that now legends are no longer a combination of axis and texts, but a new type in itself. The command "get(gcf,'children')" now return a nx1 graphics object, where the 'legend' element is different from the 'axis' element.

We have fixed issue 1) however it is quite difficult to fix issue 2). I got as far as correctly formatting legends with 1 data series only, by passing the legend handle to ProcessTicks() and ProcessTexts() functions. However this is not of much use.

Please let us know about your plans on updating this fantastic function, which is now a crucial part of our workflow.

Many thanks,
LM

**Comment by fbyland** [comment]
Is there any progress yet regarding this problem?

**Comment by jamescamdenmartin** [comment]
Submitted a pull request that fixes the legend issue. Tested in Matlab 2017, but it may also fix it in 2014a?
