### ISSUE TITLE
No math environment possible anymore & no possibility of two y-axis

### ISSUE THREAD

**Issue by fips12** [zprime/matlabfrag#17]
Is there a reason, why the math environment is not usable any more after the last update? Because so I am not able to appy the same design of formulas as used in my thesis, as shown in the example.

Is there any possibilty to use it for a figure with two y-axis. Like for example:

```
x=1:0.1:100;
y=sin(x);
y2=sin(x)-1;
fig = figure;
yyaxis left
plot(x,y)
title('$F_z$');
text(pi,0,'$\leftarrow \sin{x} \frac{abc}{de_f}$')
xlabel('yabdxd $F_x\cdot\ y\cdot\phi$')
ylabel('$\varphi$')

ylim([-2 2])

yyaxis right
plot(x,y2)
ylabel('$\varphi_2$')
l = legend({'abcyasdfasdfadsfadsfasdfa','$F_x$'});

matlabfrag('test');
```

?
Thanks a lot in advance!

**Comment by jamescamdenmartin** [comment]
I should have a fix for this tomorrow.

**Comment by jamescamdenmartin** [comment]
![image](https://user-images.githubusercontent.com/12981040/36571722-d46d6374-17fd-11e8-87e9-9843591923ed.png)
There's a slight issue in that the legend box is larger than it needs to be for the text, but the rest of your example looks correct now, right?

**Comment by fips12** [comment]
Thank you for the changes! But the left y-axis has still a different font (courier). It would be very nice of you, if you could fix this, please.

**Comment by jamescamdenmartin** [comment]
I started on the two y-axis issue but it's not completely straightforward to fix. See https://github.com/zprime/matlabfrag/issues/19

If I have time this week I might continue to try to fix it.
